### PR TITLE
Add functionality to include a show to be merged with the already existing artist

### PR DESCRIPTION
**Pull request by fravoll**
I have been using your shuffler for months now and am a big fan of the functionality. However, as I really like the [Die Dr3i](https://open.spotify.com/show/5cgMSSNAioVK0STCTlvo0z) episodes, I was missing them in my rotation.
With the PR I added an optional env variable for a show (e.g. 5cgMSSNAioVK0STCTlvo0z) which is then fetched next to the artist albums and then added to the rotation.

In case the env variable is empty the app works as it used to.

Additionally I added a few new filter criteria to exclude the audiobooks for movies, which do not use the original speakers and are therefore not considered part of the series by some.

Let me know what you think :)
Would be happy to see this version hosted on ddf.gutsman.de

Cheers

### CODE REVIEW

**Comment by b0wter** [comment]
I am very glad to hear that this project brought you joy and thanks a lot for contributing! :)
I've skimmed your changes and they look very nice. I will get back to you in a couple of days. I'd like to run things locally first.

FYI: there is also an improved version of this project, you can find [a live version here](https://kassettenwechsler.de/) and the [source code here](https://github.com/AlbumShuffler). Let me know what you think :)
(my email is displayed on my [profile](https://github.com/b0wter) as long as you're logged into GitHub)

**Comment by fravoll** [comment]
Thanks a lot for the feedback!
Really appreciating your effort for coding and hosting this app! The style of the new version is amazing.
I saw you already added the "Die Dr3i" there as a source. Nice that functionality for playlists was already provided.
However, as of now it would not fully fullfil my need as I would like to receive random episodes for both "??? and die Dr3i" without being limited to either one of them.
I haven't had a look at the code but maybe one feature could be to be able to select multiple "sources" in the view where you can select the artist/playlist.

**Comment by b0wter** [comment]
I've also updated the version hosted on `ddf.gutsman.de` :)

I will also bring "die Dr3i" to `kassettenwechsler.de` and make it offer the option to select multiple sources. I've played with the idea before but could not decide how to design the ui for that.

I am also thinking about adding a robust filtering solution to filter episodes by id, keywords and so on. Having the movie tie-ins really annoys me.

**Comment by fravoll** [comment]
Awesome! Thanks a lot :)

**Comment by b0wter** [comment]
@fravoll 
I've updated https://kassettenwechsler.de 
It now supports combining artists :)

**Comment by b0wter** [comment]
@fravoll
I've remove Die Dr3i from kassettenwechsler.de since the show is no longer available. Just in case you were wondering.
If you have questions or follow-ups please open an issue [here](https://github.com/AlbumShuffler)

**Pull request merged**
